/**
 * SWS Template Registry
 * 
 * Contains the complete template definitions for all SWS worksheet types.
 * Based on the actual SWS-IPV documents from D380 manufacturing.
 */

import type {
  SwsTemplateId,
  SwsTemplateDefinition,
  SwsSectionDefinition,
  SwsHeaderFieldDefinition,
} from '@/types/d380-sws'

// ============================================================================
// STANDARD HEADER FIELDS
// ============================================================================

const STANDARD_HEADER_FIELDS: SwsHeaderFieldDefinition[] = [
  {
    id: 'pdNumber',
    label: 'PD#',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 15,
    placeholder: 'PD#',
  },
  {
    id: 'projectName',
    label: 'Project Name',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 35,
    placeholder: 'Project Name',
  },
  {
    id: 'unit',
    label: 'Unit #',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 10,
    placeholder: 'Unit #',
  },
  {
    id: 'panel',
    label: 'Panel',
    type: 'TEXT',
    required: false,
    canAutoCompute: true,
    widthPercent: 15,
    placeholder: 'Panel',
  },
  {
    id: 'date',
    label: 'Date',
    type: 'DATE',
    required: true,
    canAutoCompute: true,
    widthPercent: 12,
    placeholder: 'Date',
  },
  {
    id: 'revision',
    label: 'Rev',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 8,
    placeholder: 'Rev',
  },
]

const BOX_HEADER_FIELDS: SwsHeaderFieldDefinition[] = [
  {
    id: 'pdNumber',
    label: 'PD#',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 15,
    placeholder: 'PD#',
  },
  {
    id: 'projectName',
    label: 'Project Name',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 35,
    placeholder: 'Project Name',
  },
  {
    id: 'unit',
    label: 'Unit #',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 10,
    placeholder: 'Unit #',
  },
  {
    id: 'box',
    label: 'Box',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 15,
    placeholder: 'Box',
  },
  {
    id: 'date',
    label: 'Date',
    type: 'DATE',
    required: true,
    canAutoCompute: true,
    widthPercent: 12,
    placeholder: 'Date',
  },
  {
    id: 'revision',
    label: 'Rev',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 8,
    placeholder: 'Rev',
  },
]

const CONSOLE_HEADER_FIELDS: SwsHeaderFieldDefinition[] = [
  {
    id: 'pdNumber',
    label: 'PD#',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 15,
    placeholder: 'PD#',
  },
  {
    id: 'projectName',
    label: 'Project Name',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 30,
    placeholder: 'Project Name',
  },
  {
    id: 'unit',
    label: 'Unit #',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 10,
    placeholder: 'Unit #',
  },
  {
    id: 'bays',
    label: '# Bays',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 10,
    placeholder: '# Bays',
  },
  {
    id: 'date',
    label: 'Date',
    type: 'DATE',
    required: true,
    canAutoCompute: true,
    widthPercent: 12,
    placeholder: 'Date',
  },
  {
    id: 'revision',
    label: 'Rev',
    type: 'TEXT',
    required: true,
    canAutoCompute: true,
    widthPercent: 8,
    placeholder: 'Rev',
  },
]

// ============================================================================
// PANEL BUILD/WIRE TEMPLATE (Standard)
// ============================================================================

const PANEL_BUILD_WIRE_SECTIONS: SwsSectionDefinition[] = [
  {
    id: 'obtain-parts',
    workElementNumber: 1,
    description: 'Obtain the kitted parts from the rack. Verify the PD#. Review the Layout, check for discrepancies.',
    references: ['WI 5.3.0.5-02'],
    requiresAuditor: false,
    cycleTime: '0:20',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    processSteps: [
      {
        id: 'verify-revision',
        text: 'Verify the latest Revision (check the cover sheet for any special requirements). Fill in the Project information above on this form. Stamp the layout drawing with the "Working Copy" stamp and fill in the information.',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
      {
        id: 'verify-panel',
        text: 'Verify the correct panel - attach the panel ID label and fill in the project information.(Do not install directly to the panel)',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
      {
        id: 'notify-discrepancies',
        text: 'Notify the Team Leader/Lead about discrepancies (Missing Parts, etc.). Follow the first unit on a multi-unit project.',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
    ],
  },
  {
    id: 'prepare-build',
    workElementNumber: 2,
    description: 'Prepare to build the panel',
    references: ['QAS 500', 'EDM F11.2'],
    requiresAuditor: false,
    cycleTime: '0:30',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    processSteps: [
      {
        id: 'measure-cut-prelayout',
        text: 'Measure, cut and pre-lay out rails, large components and pan duct to verify fit for both pre and non-pre drilled (template) panels.',
        isKeyPoint: false,
        requiresCheckOff: true,
        subSteps: [
          'Verify no drill zones using the overall layout for non-pre-drilled panels. Unistruts are shown on overall layout for consoles.',
          'Mark any pan duct that covers a mounting hole through the under side of the panel. For all Products (OnSkid), ensure the center mounting holes are open (vertical panduct).',
        ],
      },
    ],
  },
  {
    id: 'drill-bond',
    workElementNumber: 3,
    description: 'Drill and Bond the Panel according to the layout (overall layout if off-skid) for Frame Ground.',
    symbol: 'SFT',
    references: ['EDM F11.2'],
    requiresAuditor: true,
    auditorReference: '3/8" Nutcert Verification',
    cycleTime: '1:00',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    verificationCheckpoints: [
      {
        id: 'nutcert-verification',
        label: '3/8" Nutcert Verification',
        description: 'For the Panel Hanging Holes, or any 3/8" hole, ensure nutcerts are properly seated.',
        requiresAuditorStamp: true,
        columnLabel: '3/8" Nutcert Verification',
      },
    ],
    processSteps: [
      {
        id: 'drill-rails',
        text: 'Using a vice, drill the rails, install nutcerts and end caps and bond the panel.',
        isKeyPoint: false,
        requiresCheckOff: true,
        subSteps: [
          'Remove the painted surfaces for the installation of the frame grounds (bonding). Clean the debris from the panel.',
          'For the Panel Hanging Holes, or any 3/8" hole, ensure nutcerts are properly seated. Get visual stamp in Auditor column.',
        ],
      },
    ],
  },
  {
    id: 'panel-components',
    workElementNumber: 4,
    description: 'Install all panel mounted components (i.e. PLC Chassis, Power Supply, Fan, Filter, Bus Bar, BUOS, CGCM, Shunt Relay, Pnl Mount Diode, etc.)',
    references: ['EDM F11.02', 'QAS 500', 'QAS 850'],
    requiresAuditor: false,
    cycleTime: '0:30',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    notes: ['NOTE: See Standard Work Book for details on part installation'],
    processSteps: [
      {
        id: 'install-panel-components',
        text: 'Install all panel mounted components (ensure there is enough clearance between the Bus Bar and rail)',
        isKeyPoint: false,
        requiresCheckOff: true,
        subSteps: [
          'Install short standoffs in the holes for the shock guard.',
          'Ensure ground checks are conducted if required.',
          'Secure the PLC keys to the chassis so they do not get lost',
        ],
      },
    ],
  },
  {
    id: 'standoffs-rails',
    workElementNumber: 5,
    description: 'Install the standoffs, din rails and ground wires per layout drawing',
    references: ['QAS 500', 'EDM F11.2'],
    requiresAuditor: false,
    cycleTime: '0:30',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    processSteps: [
      {
        id: 'install-standoffs',
        text: 'Install the standoffs, rails, frame grounds and ground hardware.',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
    ],
  },
  {
    id: 'rail-components',
    workElementNumber: 6,
    description: 'Install all rail mounted components per the layout drawing.',
    references: ['QAS 500'],
    requiresAuditor: true,
    auditorReference: '1444 Verification',
    cycleTime: '1:30',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    verificationCheckpoints: [
      {
        id: '1444-verification',
        label: '1444 Verification',
        description: 'For the 1444 Vibration models, ensure the base dials are set per layout drawing prior to installing the modules.',
        requiresAuditorStamp: true,
        columnLabel: '1444 Verification',
      },
    ],
    processSteps: [
      {
        id: 'install-rail-components',
        text: 'Install rail mounted components per the layout drawing. All components start at the top of rails unless dimensioned otherwise or clearly shown starting from the bottom.',
        isKeyPoint: false,
        requiresCheckOff: true,
        subSteps: [
          'Ensure I/O module base dials are set prior to installing the modules.',
          'Install the fuse, fuse amperage labels and terminal markers.',
        ],
      },
      {
        id: '1444-models',
        text: 'For the 1444 Vibration models, ensure the base dials are set per layout drawing prior to installing the modules. Get visual stamp in Auditor column. Verify rail isolation then install component and verify component/rail isolation.',
        isKeyPoint: true,
        requiresCheckOff: true,
        verificationType: '1444',
      },
    ],
  },
  {
    id: 'blue-labels',
    workElementNumber: 7,
    description: 'Install the blue component labels per layout.',
    references: ['QAS 834'],
    requiresAuditor: false,
    cycleTime: '1:00',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    processSteps: [
      {
        id: 'install-blue-labels',
        text: 'Install blue component labels using the label installation tool. Follow Shop floor examples (wall/shop aids). Verify labels will be visible after the pan duct is installed.',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
    ],
  },
  {
    id: 'panduct',
    workElementNumber: 8,
    description: 'Install and secure the panduct.',
    references: ['QAS 503/505'],
    requiresAuditor: false,
    cycleTime: '0:20',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    processSteps: [
      {
        id: 'install-panduct',
        text: 'Using the pan duct finger cutters, remove any fingers that will interfere with the wiring or wire routing.',
        isKeyPoint: false,
        requiresCheckOff: true,
        subSteps: [
          'Install the pan duct. Ensure Labels are visible and it is not touching or is interfering with the operation of the components.',
        ],
      },
    ],
  },
  {
    id: 'clean-complete-build',
    workElementNumber: 9,
    description: 'Clean the debris and complete the panel',
    references: ['WI 5.7.2-01'],
    requiresAuditor: false,
    cycleTime: '0:20',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    processSteps: [
      {
        id: 'label-shortages',
        text: 'Label all part shortages with a sticker and document in the comment section to the right',
        isKeyPoint: false,
        requiresCheckOff: true,
        subSteps: [
          'Look over panel and verify it is built to print. All discrepancies/deviations documented with an MRCA#.',
          'Stamp the Build Up portion of the Panel ID label',
          'Notify Team Leader/Lead of any shortages, issues and the panel is ready for visual inspection. (Team Leader/Lead will assign)',
        ],
      },
    ],
  },
  {
    id: 'prepare-wire',
    workElementNumber: 10,
    description: 'Prepare to wire the panel. Verify if it is a multi-unit project.',
    references: ['WI 5.3.0.5-02'],
    requiresAuditor: false,
    cycleTime: '0:30',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    notes: [
      'NOTE: Highlight all wires or components (resistors, diodes, etc.) installed throughout the wiring process using the same color used to highlight your badge number. All wires leaving the panel are tagged with a destination individually or in a bundle.',
    ],
    processSteps: [
      {
        id: 'fill-project-info',
        text: 'Fill in the Project information above on this form.',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
      {
        id: 'verify-auditor-stamp',
        text: 'Ensure Auditor stamp is complete for Panel Build prior to starting the wiring. Notify Team Leader if not completed.',
        isKeyPoint: false,
        requiresCheckOff: true,
        subSteps: [
          'Verify the latest revision. Note cover sheet for any special requirements.',
          'Stamp working copy of wire list and layout drawing. Highlight your badge number with the same color you will use on the wire list.',
          'For multi unit project, verify routing on the first unit. Notify Team Leader if incorrect. Wires will route under the rail first for any component that does not have pan duct next to it.',
        ],
      },
    ],
  },
  {
    id: 'start-wiring',
    workElementNumber: 11,
    description: 'Start wiring the panel',
    references: ['QAS 503/505/850', 'EDM F11.2'],
    requiresAuditor: false,
    cycleTime: '2:00',
    hasTimeTracking: true,
    supportsMultiBadge: true,
    notes: ['Note: For OffSkid consoles, check overall layout to verify wire routing. Standard routing is Left to Right, Top to Bottom'],
    processSteps: [
      {
        id: 'install-grounds',
        text: 'Install all ground wires. Console - Bus Bar wires route to the bottom. Boxes - Bus Bar wires will route to the top. (Space permitting)',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
      {
        id: 'install-jumpers',
        text: 'Install all jumpers, both mechanical and wires including thermistors as required, resistors and diodes (verify polarity).',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
    ],
  },
  {
    id: 'wire-relays',
    workElementNumber: 12,
    description: 'Wire the relays/timers',
    references: ['QAS 500/503/505'],
    requiresAuditor: false,
    cycleTime: '3:00',
    hasTimeTracking: true,
    supportsMultiBadge: true,
    processSteps: [
      {
        id: 'pull-test-required',
        text: 'All wires being installed require a pull test to ensure they are tight and a visual for stray strands (bird caging)',
        isKeyPoint: true,
        requiresCheckOff: true,
        verificationType: 'PULL_TEST',
      },
      {
        id: 'wire-relays-timers',
        text: 'Start wiring relays and timers. This will include 14/16ga. Use the correct hardware (short vs long ferrules, etc). Do not wire the Sync Check Relay (Red or Blue AC wires). Ensure all circuit numbers are visible',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
    ],
  },
  {
    id: 'wire-buos',
    workElementNumber: 13,
    description: 'Wire the BUOS/Continue with the smaller gauge wires',
    references: ['QAS 500/503/505'],
    requiresAuditor: true,
    auditorReference: 'AENTR ONLY Pull Test, 0v & 24v',
    cycleTime: '4:30',
    hasTimeTracking: true,
    supportsMultiBadge: true,
    verificationCheckpoints: [
      {
        id: 'aentr-pull-test',
        label: 'AENTR Pull Test',
        description: 'Perform separate pull test on AENTR (or equiv) modules 0v and 24v leads.',
        requiresAuditorStamp: true,
        columnLabel: 'AENTR ONLY Pull Test, 0v & 24v',
      },
    ],
    processSteps: [
      {
        id: 'pull-test-required-2',
        text: 'All wires being installed require a pull test to ensure they are tight and a visual for stray strands (bird caging)',
        isKeyPoint: true,
        requiresCheckOff: true,
        verificationType: 'PULL_TEST',
      },
      {
        id: 'wire-buos',
        text: 'Wire and create harness for the Back Up Overspeed Module. Terminate as required.',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
      {
        id: 'aentr-pull-test',
        text: 'Perform separate pull test on AENTR (or equiv) modules 0v and 24v leads. Provide IPV stamp when complete.',
        isKeyPoint: true,
        requiresCheckOff: true,
        verificationType: 'AENTR',
      },
      {
        id: 'remaining-wires',
        text: 'Install the remaining wires starting with smaller wires (20ga) first and continuing progressing up in size until all white wires have been installed.',
        isKeyPoint: false,
        requiresCheckOff: true,
        subSteps: [
          'Maintain IS (blue pan duct wiring) separation if required.',
        ],
      },
    ],
  },
  {
    id: 'wire-diodes-ac',
    workElementNumber: 14,
    description: 'Wire Flyback Diodes and Install AC wires',
    references: ['QAS 500/503/505'],
    requiresAuditor: false,
    cycleTime: '3:30',
    hasTimeTracking: true,
    supportsMultiBadge: true,
    processSteps: [
      {
        id: 'pull-test-required-3',
        text: 'All wires being installed require a pull test to ensure they are tight and a visual for stray strands (bird caging)',
        isKeyPoint: true,
        requiresCheckOff: true,
        verificationType: 'PULL_TEST',
      },
      {
        id: 'wire-diodes',
        text: 'Wire the Flyback Diodes per wire list. Ensure circuit numbers and polarity on the component is visible.',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
      {
        id: 'install-ac',
        text: 'Install the AC (red/blue) wires starting from the DECS. Use expando sleeving for sharp edge protection or isolation. Maintain separation from the white wires use spiral wrap for white wires.',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
    ],
  },
  {
    id: 'cables-comm',
    workElementNumber: 15,
    description: 'Install Cables and Internal Communication Cables',
    references: ['QAS 503/505/834'],
    requiresAuditor: false,
    cycleTime: '1:30',
    hasTimeTracking: true,
    supportsMultiBadge: true,
    notes: ['Note: Any wire or cable that deforms the pan duct must have the pan duct finger removed to allow the wire(s) to lay flat.'],
    processSteps: [
      {
        id: 'install-cables',
        text: 'Install all cables. Install smaller, then larger cables followed by all communication cables that will terminate within the panel. Apply labels per shop floor example.',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
    ],
  },
  {
    id: 'clean-complete-wire',
    workElementNumber: 16,
    description: 'Clean the debris and complete the panel',
    references: ['WI 5.7.2-01'],
    requiresAuditor: false,
    cycleTime: '0:30',
    hasTimeTracking: true,
    supportsMultiBadge: false,
    processSteps: [
      {
        id: 'ensure-shortages-documented',
        text: 'Ensure all shortages are documented',
        isKeyPoint: false,
        requiresCheckOff: true,
      },
      {
        id: 'verify-wired',
        text: 'Look over panel and verify it is completely wired per wire list. All discrepancies/deviations documented with an MRCA#',
        isKeyPoint: false,
        requiresCheckOff: true,
        notes: ['Verify that any wires going to large terminals are properly terminated with the correct strip length'],
        subSteps: [
          'Stamp the wiring portion of the Panel ID label',
          'Notify Team Leader/Lead of any shortages, issues and the panel is ready for visual inspection. (Team Leader/Lead will assign)',
        ],
      },
    ],
  },
  {
    id: 'stamp-complete',
    workElementNumber: 17,
    description: 'Stamp as Complete',
    references: ['WI 5.7.2-01'],
    requiresAuditor: true,
    auditorReference: 'Auditor: Stamp the IPV portion of the panel ID label. Ensure a Pull Test was performed on all wires and a visual for bird caging and insulation crimping.',
    cycleTime: '0:05',
    hasTimeTracking: false,
    supportsMultiBadge: false,
    processSteps: [],
  },
]

// ============================================================================
// TEMPLATE DEFINITIONS
// ============================================================================


export const PANEL_BUILD_WIRE_TEMPLATE: SwsTemplateDefinition = {
  id: 'PANEL_BUILD_WIRE',
  swsIpvId: 'SWS-IPV_D380_ASY_PNL BUILD-WIRE_1.2',
  name: 'Panel Build Up/Wire',
  shortLabel: 'Panel',
  description: 'Panel build up and wiring with time tracking columns',
  category: 'PANEL',
  stageScopes: ['BUILD_UP', 'WIRING'],
  revisionLevel: '1.2',
  revisionDate: '3/11/2026',
  processDescription: 'PANEL BUILD & WIRE',
  detectionPatterns: [
    {
      type: 'KEYWORD',
      pattern: /DIGITAL|DIGI/i,
      keywords: ['DIGITAL', 'DIGI'],
      confidence: 'HIGH',
      priority: 15,
    },
  ],
  sections: PANEL_BUILD_WIRE_SECTIONS, // Same sections, different format
  headerFields: STANDARD_HEADER_FIELDS,
  references: ['WI 5.7.2-01', 'WI 5.7.2-05'],
  footerText: 'Caterpillar: Confidential Green',
  pageCount: 2,
  supportsTabletMode: true,
  computedFields: [
    { fieldId: 'pdNumber', sourcePath: 'project.pdNumber', allowOverride: true },
    { fieldId: 'projectName', sourcePath: 'project.name', allowOverride: true },
    { fieldId: 'unit', sourcePath: 'assignment.unit', allowOverride: true },
    { fieldId: 'panel', sourcePath: 'assignment.panelName', allowOverride: true },
    { fieldId: 'revision', sourcePath: 'project.revision', allowOverride: true },
    { fieldId: 'date', sourcePath: 'assignment.date', transform: 'FORMAT_DATE', allowOverride: true },
  ],
  overridePolicy: {
    overridableFields: ['pdNumber', 'projectName', 'unit', 'panel', 'date', 'revision'],
    requiresOverrideReason: false,
    logOverrides: true,
    warnAfterOverrideCount: 3,
  },
}

export const BASIC_BLANK_PANEL_TEMPLATE: SwsTemplateDefinition = {
  id: 'BASIC_BLANK_PANEL',
  swsIpvId: 'SWS-IPV_D380_ASSY_SMALL-BLANK PANEL_PILOT',
  name: 'Basic/Blank Panels',
  shortLabel: 'Blank Panel',
  description: 'Assembly for Basic/Blank Panels (Prox, Media, Terminal Strip, Marshalling, NTB Panels etc.)',
  category: 'PANEL',
  stageScopes: ['BUILD_UP', 'WIRING'],
  revisionLevel: 'A.1',
  revisionDate: '12/12/2024',
  processDescription: 'Assembly For Basic/ Blank Panels (Prox, Media, Terminal Strip, Marshalling, NTB Panels etc.)',
  detectionPatterns: [
    {
      type: 'KEYWORD',
      pattern: /BLANK|BASIC|PROX|MEDIA|TERMINAL\s*STRIP|MARSHALLING|NTB/i,
      keywords: ['BLANK', 'BASIC', 'PROX', 'MEDIA', 'TERMINAL STRIP', 'MARSHALLING', 'NTB'],
      confidence: 'HIGH',
      priority: 20,
    },
  ],
  sections: [
    {
      id: 'verify-drawings',
      workElementNumber: 1,
      description: 'Verify Drawings and Parts',
      references: ['QAS 500', 'WI 5.3.0.5-02'],
      requiresAuditor: false,
      cycleTime: '0:15',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'verify-revision',
          text: 'Verify the latest Revision (check the cover sheet for any special requirements). Fill in the "Working Copy" stamp.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'obtain-parts',
          text: 'Obtain the kitted parts and verify the PD#. Install panel ID label. If a multiple unit project, follow previous unit.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'build-panel',
      workElementNumber: 2,
      description: 'Build the Panel',
      references: ['QAS 500', 'QAS 503', 'QAS 505'],
      requiresAuditor: false,
      cycleTime: '1:00',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'measure-drill-bond',
          text: 'Measure, drill and bond the panel per the layout dwg. Cut pan duct and rails if required.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Install nutcerts, standoffs, din rails, bus bars and ground wires as required.',
            'Install components on the rails and apply blue labels. Install Pan Duct(if applicable). Stamp off the Build Up portion of the Panel ID label.',
          ],
        },
      ],
    },
    {
      id: 'wire-panel',
      workElementNumber: 3,
      description: 'Wire the Panel',
      references: ['QAS 503/505'],
      requiresAuditor: false,
      cycleTime: '1:00',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'pull-test',
          text: 'All wires installed require a pull test to ensure tightness, a visual for stray strands and crimped insulation.',
          isKeyPoint: true,
          requiresCheckOff: true,
          verificationType: 'PULL_TEST',
        },
        {
          id: 'wire-panel',
          text: 'Wire the Panel if required per QAS 503/505. Stamp off the Wire portion of the Panel ID label.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'install-in-box',
      workElementNumber: 4,
      description: 'Install Panel in the box (if applicable)',
      references: ['SWS-IPV_D380_ASSY_Box Build Up'],
      requiresAuditor: false,
      cycleTime: '1:00',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'visual-panel',
          text: 'Visual panel prior to dropping in the box (Get auditor stamp).',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'drop-assemble',
          text: 'Drop panel and assemble the box. (Reference the Box Build Up SWS).',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'ipv',
      workElementNumber: 5,
      description: 'In-Process Validation',
      references: ['WI 5.7.2-01'],
      requiresAuditor: true,
      auditorReference: 'Auditor: Verify that all the above items have been completed including a wire pull test and a visual for Bird Caging and Insulation Crimping. Stamp the IPV portion of the Panel ID Label.',
      cycleTime: '0:20',
      hasTimeTracking: false,
      supportsMultiBadge: false,
      notes: ['This section must be completed by someone who did not complete the above sequences.'],
      processSteps: [],
    },
  ],
  headerFields: STANDARD_HEADER_FIELDS,
  references: ['WI 5.7.2-01', 'WI 5.7.2-05'],
  footerText: 'Caterpillar: Confidential Green',
  pageCount: 1,
  supportsTabletMode: true,
  computedFields: [
    { fieldId: 'pdNumber', sourcePath: 'project.pdNumber', allowOverride: true },
    { fieldId: 'projectName', sourcePath: 'project.name', allowOverride: true },
    { fieldId: 'unit', sourcePath: 'assignment.unit', allowOverride: true },
    { fieldId: 'panel', sourcePath: 'assignment.panelName', allowOverride: true },
    { fieldId: 'revision', sourcePath: 'project.revision', allowOverride: true },
  ],
  overridePolicy: {
    overridableFields: ['pdNumber', 'projectName', 'unit', 'panel', 'date', 'revision'],
    requiresOverrideReason: false,
    logOverrides: true,
    warnAfterOverrideCount: 3,
  },
}

export const BOX_BUILD_UP_TEMPLATE: SwsTemplateDefinition = {
  id: 'BOX_BUILD_UP',
  swsIpvId: 'SWS-IPV_D380_ASSY_Box Build Up_0.3',
  name: 'Box Build Up',
  shortLabel: 'Box Build',
  description: 'Assembly for Box Build Up',
  category: 'BOX',
  stageScopes: ['BOX_BUILD'],
  revisionLevel: '0.3',
  revisionDate: '1/02/2026',
  processDescription: 'Assembly For Box Build Up',
  detectionPatterns: [
    {
      type: 'ENCLOSURE_TYPE',
      pattern: /BOX/i,
      confidence: 'HIGH',
      priority: 10,
    },
    {
      type: 'KEYWORD',
      pattern: /BOX\s*BUILD|ENCLOSURE/i,
      keywords: ['BOX BUILD', 'ENCLOSURE'],
      confidence: 'HIGH',
      priority: 15,
    },
  ],
  sections: [
    {
      id: 'obtain-box',
      workElementNumber: 1,
      description: 'Obtain the box',
      symbol: 'SFN',
      references: ['SFN/SOP'],
      requiresAuditor: false,
      cycleTime: '0:15',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      notes: ['Ensure you have a spotter.'],
      processSteps: [
        {
          id: 'verify-box',
          text: 'Verify box part #, PD/CM# with the pick tag and layout (use legal drawing packet).',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'check-damage',
          text: 'Check for obvious damage prior to moving (notify Team Leader immediately if damaged). Transport the box to the staging area.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'inspect-box',
      workElementNumber: 2,
      description: 'Inspect the box',
      references: ['QAS 500', 'SOP'],
      requiresAuditor: false,
      cycleTime: '0:45',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'inspect-box',
          text: 'Inspect the Box.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'If the box is for After Market projects, install hole plugs prior to panel installation',
            'Get the crane to lay the box flat on the pallet (if applicable).',
            'Check for torque paint on the drain and vent plugs.',
            'Further inspect the physical condition of the box (scratches, dents, rust, gaskets, door opening/closing, etc.).',
            'Verify Certification and put the Project Information Label on the box.',
          ],
        },
      ],
    },
    {
      id: 'prepare-drop-panels',
      workElementNumber: 3,
      description: 'Prepare the box and drop the panels into the box',
      references: ['SFN/SOP', 'QAS 850'],
      requiresAuditor: false,
      cycleTime: '0:45',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      notes: ['In the case of boxes that do not require door build up or crosswire, complete step 4 before completing step 3'],
      processSteps: [
        {
          id: 'apply-lubricant',
          text: 'Apply lubricant to box panel mounting studs and bonded points on the panels. Install the panels using the crane. The PLC panel should be installed first (when applicable). Use the correct hardware (stainless steel, zinc, etc.).',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Install ground straps to connect the panels (when applicable).',
            'Secure panels to the box and apply torque paint on 3/8 hardware only (tight plus 1/4 turn).',
          ],
        },
      ],
    },
    {
      id: 'hang-box',
      workElementNumber: 4,
      description: 'Prepare and hang the box on the rack',
      references: ['SFN/SOP', 'COSP'],
      requiresAuditor: false,
      cycleTime: '1:00',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'use-lifting-tools',
          text: 'Use the proper lifting tools (overhead crane/box lifting device) to hang the box. You must be trained before using the devices.',
          isKeyPoint: true,
          requiresCheckOff: true,
          subSteps: [
            'Set mounting studs on the rack with proper spacing for the box (verify location). Obtain tools and hardware to secure the box to the rack.',
            'Hang and secure the box (using 2 people).',
          ],
        },
      ],
    },
    {
      id: 'obtain-kitted-parts',
      workElementNumber: 5,
      description: 'Obtain kitted parts. Review/ Verify drawings',
      references: ['WI 5.3.0.5-02'],
      requiresAuditor: false,
      cycleTime: '0:15',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'check-cover-sheet',
          text: 'Check the Working Copy Coversheet for the latest revision and any special requirements.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Ensure the Layout drawing has been stamped with the working copy stamp.',
            'If a multiple unit project, verify build of previous unit. (If previous unit is incorrect, notify Team Leader)',
          ],
        },
      ],
    },
    {
      id: 'box-build-up',
      workElementNumber: 6,
      description: 'Begin box build-up',
      references: ['QAS 500'],
      requiresAuditor: false,
      cycleTime: '1:30',
      hasTimeTracking: true,
      supportsMultiBadge: true,
      processSteps: [
        {
          id: 'install-door-switches',
          text: 'Install box Components',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Install all door switches for both left and right doors (keep the keys with components). Install switches from the bottom up.',
            'Install fire system door components (install component side ground wires before installing the components).',
            'Install the Horn and Display. Label Display software box with P.D./C.M. #, Unit name and # and place in the designated area.',
            'In case of a NAP Port, Install label prior to installing device. If no NAP Port, but cutout is there, install blank cover.',
            'Install ground straps from the door(s) to the box.',
          ],
        },
      ],
    },
    {
      id: 'install-side-rails',
      workElementNumber: 7,
      description: 'Install pre-assembled (wired) and non assembled side rails',
      references: ['QAS 500'],
      requiresAuditor: false,
      cycleTime: '1:00',
      hasTimeTracking: true,
      supportsMultiBadge: true,
      processSteps: [
        {
          id: 'install-rails',
          text: 'Install box rails, complete the following:',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'For non-preassembled rails: Cut the side rails according to the layout and install nutcerts and end caps.',
            'Mount the rails to the box (make sure side rails do not cover any drain, vent plugs or access holes).',
            'Install components on the rails (make sure the components do not interfere with the harness clamps). Install terminal markers, fuses and fuse labels.',
            'For pre-wired rail, remove the rail from the template (including stand offs) and install. Install side rail frame grounds.',
            'Open and close the door(s) to ensure that nothing is interfering',
            'If box has a vent at on the top (typically left side) replace it with a plug (SPN: 1053051-59) from floorstock using the -20 & -30 hardware. No torque paint is needed for the plug.',
          ],
        },
      ],
    },
    {
      id: 'install-blue-labels',
      workElementNumber: 8,
      description: 'Install blue labels',
      references: ['QAS 834'],
      requiresAuditor: false,
      cycleTime: '0:30',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'install-labels',
          text: 'Install blue labels per print (use template for door switches). See Team Leader or box display for label placement reference if needed.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Install tie wraps on switches for wire routing. Install Cable Reference ID on switches with pre-installed cables.',
          ],
        },
      ],
    },
    {
      id: 'install-external-labels',
      workElementNumber: 9,
      description: 'Install external labels and placards',
      references: ['QAS 834'],
      requiresAuditor: false,
      cycleTime: '0:30',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'verify-language',
          text: 'Verify language, (if single or dual language) and label type, (Working Copy Cover Sheet).',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Use templates to install labels and placards per drawing (switch, warning, Turbotronic/Data plates, etc.). Use the Inspection Guidelines for placement. See the Team Leader for specific labels.',
          ],
        },
      ],
    },
    {
      id: 'clean-prepare',
      workElementNumber: 10,
      description: 'Clean area and prepare for wiring.',
      references: ['WI 5.7.2-01'],
      requiresAuditor: false,
      cycleTime: '0:30',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'clean-debris',
          text: 'Clean any debris in and around the box (including table).',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Gather paperwork to submit for Build Up Visual. Document discrepancies/shortages. Notify Team Leader/Lead of completion.',
          ],
        },
      ],
    },
    {
      id: 'stamp-complete',
      workElementNumber: 11,
      description: 'Stamp as Complete',
      references: ['WI 5.7.2-01'],
      requiresAuditor: true,
      auditorReference: 'Auditor: The Visual is Completed. Tally Discrepancies below.',
      cycleTime: '0:05',
      hasTimeTracking: false,
      supportsMultiBadge: false,
      processSteps: [],
    },
  ],
  headerFields: BOX_HEADER_FIELDS,
  references: ['WI 5.7.2-01', 'WI 5.7.2-05'],
  footerText: 'Caterpillar: Confidential Green',
  pageCount: 2,
  supportsTabletMode: true,
  computedFields: [
    { fieldId: 'pdNumber', sourcePath: 'project.pdNumber', allowOverride: true },
    { fieldId: 'projectName', sourcePath: 'project.name', allowOverride: true },
    { fieldId: 'unit', sourcePath: 'assignment.unit', allowOverride: true },
    { fieldId: 'box', sourcePath: 'assignment.boxName', allowOverride: true },
    { fieldId: 'revision', sourcePath: 'project.revision', allowOverride: true },
  ],
  overridePolicy: {
    overridableFields: ['pdNumber', 'projectName', 'unit', 'box', 'date', 'revision'],
    requiresOverrideReason: false,
    logOverrides: true,
    warnAfterOverrideCount: 3,
  },
}

export const BOX_CROSS_WIRE_TEMPLATE: SwsTemplateDefinition = {
  id: 'BOX_CROSS_WIRE',
  swsIpvId: 'SWS-IPV_D380_ASSY_Box Cross Wire_0.1',
  name: 'Box Cross Wire',
  shortLabel: 'Box Cross Wire',
  description: 'Assembly for Box Cross Wiring',
  category: 'CROSS_WIRE',
  stageScopes: ['CROSS_WIRING'],
  revisionLevel: '0.1',
  revisionDate: '05/28/2025',
  processDescription: 'Assembly For Box Cross Wiring',
  detectionPatterns: [
    {
      type: 'ENCLOSURE_TYPE',
      pattern: /BOX/i,
      confidence: 'MEDIUM',
      priority: 5,
    },
    {
      type: 'KEYWORD',
      pattern: /BOX\s*CROSS|CROSS\s*WIRE.*BOX/i,
      keywords: ['BOX CROSS', 'CROSS WIRE'],
      confidence: 'HIGH',
      priority: 20,
    },
  ],
  sections: [
    {
      id: 'prepare-wire',
      workElementNumber: 1,
      description: 'Prepare to wire box',
      references: ['WI 5.7.2-01', 'WI 5.3.0.5-02'],
      requiresAuditor: false,
      cycleTime: '0:15',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      notes: ['Hours is based on Pre drilled panel.'],
      processSteps: [
        {
          id: 'auditor-complete',
          text: 'Auditor side of build up SWS is completed. (Verify with Team Leader)',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'check-revision',
          text: 'Check for latest revision. Check the cover sheet for any special requirements.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'verify-multi-unit',
          text: 'Verify if it\'s a multi unit project (note build and wire of previous unit).',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'complete-stamps',
          text: 'Complete working copy stamps on all documents that will be used to crosswire the box including layout drawings.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'crosswire-internal',
      workElementNumber: 2,
      description: 'Crosswire internal panels. Gather wire bundles',
      references: ['QAS 503', 'QAS 505'],
      requiresAuditor: false,
      cycleTime: '0:45',
      hasTimeTracking: true,
      supportsMultiBadge: true,
      processSteps: [
        {
          id: 'pull-test',
          text: 'All wires installed require a pull test to ensure tightness, a visual for stray strands and crimped insulation',
          isKeyPoint: true,
          requiresCheckOff: true,
          verificationType: 'PULL_TEST',
        },
        {
          id: 'route-terminate-panels',
          text: 'Route and terminate wires going from panel to panel. Mark crosswires going to a terminal with the same reference to identify crosswires for easier visual.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Gather the correct remaining wires by verifying PD and Unit number.',
          ],
        },
      ],
    },
    {
      id: 'side-rails',
      workElementNumber: 3,
      description: 'Route and terminate side rail(s) to box panel(s)',
      references: ['QAS 503', 'QAS 505', 'QAS 850'],
      requiresAuditor: false,
      cycleTime: '0:45',
      hasTimeTracking: true,
      supportsMultiBadge: true,
      notes: ['Tag/bundle wires going to the rail or panels'],
      processSteps: [
        {
          id: 'pull-test-2',
          text: 'All wires installed require a pull test to ensure tightness, a visual for stray strands and crimped insulation',
          isKeyPoint: true,
          requiresCheckOff: true,
          verificationType: 'PULL_TEST',
        },
        {
          id: 'route-side-rails',
          text: 'Route and terminate any side rails to the interior box panels.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Left side rail',
            'Right side rail',
            'Any ground wires and cables',
          ],
        },
      ],
    },
    {
      id: 'left-harness',
      workElementNumber: 4,
      description: 'Create Harness and wire the left side.',
      references: ['QAS 503', 'QAS 505', 'QAS 850'],
      requiresAuditor: false,
      cycleTime: '1:00',
      hasTimeTracking: true,
      supportsMultiBadge: true,
      notes: ['Tag/bundle wires going to the rail or panels'],
      processSteps: [
        {
          id: 'pull-test-3',
          text: 'All wires installed require a pull test to ensure tightness, a visual for stray strands and crimped insulation',
          isKeyPoint: true,
          requiresCheckOff: true,
          verificationType: 'PULL_TEST',
        },
        {
          id: 'wire-left-door',
          text: 'Wire the Left door',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Create harness from the left side rail (if applicable). Cut expando sleeving (clamp to clamp only).',
            'Terminate wires from the left side rail.',
            'Wire any switches and misc. components (display, horn, fire system).',
            'Terminate cables and grounds.',
          ],
        },
      ],
    },
    {
      id: 'right-harness',
      workElementNumber: 5,
      description: 'Create Harness and wire right side.',
      references: ['QAS 503', 'QAS 505'],
      requiresAuditor: false,
      cycleTime: '0:15',
      hasTimeTracking: true,
      supportsMultiBadge: true,
      processSteps: [
        {
          id: 'pull-test-4',
          text: 'All wires installed require a pull test to ensure tightness, a visual for stray strands and crimped insulation',
          isKeyPoint: true,
          requiresCheckOff: true,
          verificationType: 'PULL_TEST',
        },
        {
          id: 'wire-right-door',
          text: 'Wire the right door',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Wire any switches and misc. components (display/horn)',
            'Create door harness. Cut expando sleeving (clamp to clamp only).',
          ],
        },
      ],
    },
    {
      id: 'door-wires',
      workElementNumber: 6,
      description: 'Route and terminate door wires',
      references: ['QAS 503', 'QAS 505'],
      requiresAuditor: false,
      cycleTime: '1:30',
      hasTimeTracking: true,
      supportsMultiBadge: true,
      processSteps: [
        {
          id: 'pull-test-5',
          text: 'All wires installed require a pull test to ensure tightness, a visual for stray strands and crimped insulation',
          isKeyPoint: true,
          requiresCheckOff: true,
          verificationType: 'PULL_TEST',
        },
        {
          id: 'route-door-wires',
          text: 'Route and terminate any door wires to the box panel(s).',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Left side wires and cables.',
            'Right side wires and cables.',
          ],
        },
      ],
    },
    {
      id: 'grounds',
      workElementNumber: 7,
      description: 'Route, terminate and label ground wires',
      references: ['QAS 505', 'QAS 850', 'QAS 834'],
      requiresAuditor: false,
      cycleTime: '1:00',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'terminate-grounds',
          text: 'Terminate grounds and install labels per Shop Floor examples.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Verify gauge and color of grounds to be installed.',
            'Follow shop floor examples for label installation on the wires per termination point',
          ],
        },
      ],
    },
    {
      id: 'comm-cables',
      workElementNumber: 8,
      description: 'Install Network Communication Cables',
      references: ['QAS 503', 'QAS 505', 'QAS 834'],
      requiresAuditor: false,
      cycleTime: '0:30',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'install-comm-cables',
          text: 'Network Communication cables should be installed per layout unless it interferes with bend radius or component function.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Use Velcro to harness communication cable to existing harness.',
            'Label both ends of the communication cables. Labels should be placed 1/4" from the metal case or plastic clip and match the direction of the blue reference ID labels.',
          ],
        },
      ],
    },
    {
      id: 'submit-visual',
      workElementNumber: 9,
      description: 'Submit for Cross Wire Visual',
      references: ['WI 5.7.2-01'],
      requiresAuditor: false,
      cycleTime: '0:30',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'clean-debris',
          text: 'Clean any debris in and around the box (including the table)',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'remove-cover',
          text: 'Ensure any material used to cover the Power Supply has been removed prior to test.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'submit-visual',
          text: 'Submit for Cross Wire Visual. Notify Team Leader/Lead of completion and if there are any issues that have not been addressed.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'stamp-complete',
      workElementNumber: 10,
      description: 'Stamp as completed',
      references: ['WI 5.7.2-01'],
      requiresAuditor: true,
      auditorReference: 'Auditor: *The Visual is Completed Including a Wire Pull Test on all Cross Wires and a Visual for Bird Caging and Insulation Crimping. Tally Discrepancies below.',
      cycleTime: '0:05',
      hasTimeTracking: false,
      supportsMultiBadge: false,
      processSteps: [],
    },
  ],
  headerFields: BOX_HEADER_FIELDS,
  references: ['WI 5.7.2-01', 'WI 5.7.2-05'],
  footerText: 'Caterpillar: Confidential Green',
  pageCount: 2,
  supportsTabletMode: true,
  computedFields: [
    { fieldId: 'pdNumber', sourcePath: 'project.pdNumber', allowOverride: true },
    { fieldId: 'projectName', sourcePath: 'project.name', allowOverride: true },
    { fieldId: 'unit', sourcePath: 'assignment.unit', allowOverride: true },
    { fieldId: 'box', sourcePath: 'assignment.boxName', allowOverride: true },
    { fieldId: 'revision', sourcePath: 'project.revision', allowOverride: true },
  ],
  overridePolicy: {
    overridableFields: ['pdNumber', 'projectName', 'unit', 'box', 'date', 'revision'],
    requiresOverrideReason: false,
    logOverrides: true,
    warnAfterOverrideCount: 3,
  },
}

export const CONSOLE_BUILD_UP_PANEL_HANG_TEMPLATE: SwsTemplateDefinition = {
  id: 'CONSOLE_BUILD_UP_PANEL_HANG',
  swsIpvId: 'SWS-IPV_D380_ASSY_CON BUILD UP-Pnl Hang_B.2',
  name: 'Console Build Up / Panel Hang',
  shortLabel: 'Console Build',
  description: 'Assembly for Console Build Up / Panel Hang',
  category: 'CONSOLE',
  stageScopes: ['BOX_BUILD', 'PANEL_HANG'],
  revisionLevel: 'B.2',
  revisionDate: '10/16/2025',
  processDescription: 'Assembly For Console Build Up / Panel Hang',
  detectionPatterns: [
    {
      type: 'ENCLOSURE_TYPE',
      pattern: /CONSOLE|CON/i,
      confidence: 'HIGH',
      priority: 10,
    },
    {
      type: 'KEYWORD',
      pattern: /CONSOLE\s*BUILD|CON\s*BUILD|PANEL\s*HANG/i,
      keywords: ['CONSOLE BUILD', 'CON BUILD', 'PANEL HANG'],
      confidence: 'HIGH',
      priority: 15,
    },
  ],
  sections: [
    {
      id: 'get-console',
      workElementNumber: 1,
      description: 'Get The Console',
      symbol: 'SFN',
      references: [],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'ensure-spotter',
          text: 'Ensure you have a spotter for transporting console.',
          isKeyPoint: true,
          requiresCheckOff: true,
        },
        {
          id: 'verify-console',
          text: 'Verify console part #, PD/CM# with the pick tag (look for obvious damage prior to moving inside, if damaged notify Team Leader immediately). Use proper transporting devices for the consoles.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'inspect-install-label',
      workElementNumber: 2,
      description: 'Inspect and Install Identification Label',
      references: ['QAS 500', 'WI 5.3.0.5-02'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'verify-condition',
          text: 'Verify and check the physical condition of the console (scratches, dents, rust, gaskets, door opening/closing, etc.).',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Verify latest revision, look for any special requirements or component installation, from the Working Copy Cover Sheet.',
            'Verify certification and put the Project Information Label on the console.',
          ],
        },
      ],
    },
    {
      id: 'overhead-components',
      workElementNumber: 3,
      description: 'Install overhead components/Apply torque paint',
      references: ['QAS 500'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      notes: ['NOTE: Ensure Light Brackets does not interfere with Gland Access plates'],
      processSteps: [
        {
          id: 'install-horn',
          text: 'Horn',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'install-light',
          text: 'Light/Bracket - Install wires between lights for 3 or 4 Bay Consoles (see display).',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'install-switches',
          text: 'Correct Door Switch(s)',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'door-panels',
      workElementNumber: 4,
      description: 'Install Door Panels including longer screws for inside door panels.',
      references: ['QAS 500'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: true,
      processSteps: [
        {
          id: 'install-door-panels',
          text: 'Install door panels starting left to right and bottom to top per the layout drawing (use a flat tip screwdriver as a pry bar to decrease gaps between the panels). Install the black plastic washers on every other set of screws, ensuring one is installed at each corner of the door and corners of the HMI and other components.',
          isKeyPoint: false,
          requiresCheckOff: true,
          notes: ['**(Use torque setting 2 or 3 on the cordless screwdrivers. DO NOT OVER-TIGHTEN PLASTIC WASHER SCREWS)'],
          subSteps: [
            'Complete installation of shield bars, door ground straps and vinyl caps on exposed ground or Meter/Switch studs. Do not cover any component or ID labels.',
          ],
        },
      ],
    },
    {
      id: 'install-tcp',
      workElementNumber: 5,
      description: 'Install TCP',
      references: ['QAS 500', 'SFN'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'verify-tcp-visual',
          text: 'Before installing the TCP, ensure the TCP visual checklist is stamped off. (check with Team Leader/Lead)',
          isKeyPoint: true,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'install-display',
      workElementNumber: 6,
      description: 'Install Display (HMI)',
      references: ['QAS 500'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      notes: ['**Install HMI last on a 1 Bay Console before the Keyboard Tray**'],
      processSteps: [
        {
          id: 'install-hmi',
          text: 'Install HMI using the hardware provided by the vendor. Center HMI to minimize gaps. Ensure the hardware is tightened properly (double check once installed)',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Condense all software/extra hardware into one box. Label box with Project Name, PD/CM # and Unit # and store the box.',
          ],
        },
      ],
    },
    {
      id: 'keyboard-tray',
      workElementNumber: 7,
      description: 'Install Keyboard Tray. Do not install Keyboard Tray if the -30(x) Display is used',
      references: ['QAS 500'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      notes: ['**Install Tray last on a 1 Bay Console (after panel hanging)**'],
      processSteps: [
        {
          id: 'skip-if-30x',
          text: 'If the -30(X)Display is being used, skip this step.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'install-tray',
          text: 'Install Keyboard tray. Put keyboard inside tray and route the USB cord to the HMI. Install padding for the tray.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Ensure inside tray slides back and forth with no binding and locks in the open position.',
          ],
        },
      ],
    },
    {
      id: 'inside-door-labels',
      workElementNumber: 8,
      description: 'Install inside door panels and blue component labels',
      references: ['QAS 500', 'QAS 834'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'install-blue-labels',
          text: 'Install blue labels per print ensuring they are visible. See Team Leader/Lead or Display Console for label placement',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'door-spacers',
          text: 'Use the correct spacers for panels that are hung on the inside doors (power rail, fires system, transformer, heater, etc.). No torque paint required',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'external-labels',
      workElementNumber: 9,
      description: 'Install external labels and placards.',
      references: ['QAS 834'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'verify-label-type',
          text: 'Verify the label type (metal, phenolic), language and if it is single or dual language (cover sheet).',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Use templates to install labels and placards (warning, Turbotronic/Data plates, etc).',
          ],
        },
      ],
    },
    {
      id: 'hang-panels',
      workElementNumber: 10,
      description: 'Hang Panels in Console per the Layout Drawing using the crane and panel lift tool.',
      references: ['QAS 500', 'QAS 850'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: true,
      processSteps: [
        {
          id: 'apply-lubricant',
          text: 'Apply lubricant to all bonded mounting holes on the panels. Ensure the A and B panels are as close as possible and the gap is even from the unistrut to the boss.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Install a grn/yel 8ga. ground wire when hanging the A panel. Ensure lug is facing horizontally to the right. Install special panduct for wiring per layout drawing, if required.',
            'Tighten all bolts for the panels and apply torque paint on 3/8 hardware only (tight plus 1/4 turn).',
          ],
        },
      ],
    },
    {
      id: 'special-components',
      workElementNumber: 11,
      description: 'Install special components per layout (BN3500, HIMA, Beckwidth, etc)',
      references: ['QAS 500'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'check-special-mounting',
          text: 'Check for special mounting brackets and hardware. Check grounding/isolation of the components as needed. Install blue labels as required.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Check clearance to ensure component will not interfere with the door closing, or hit panels, harnesses or components inside the console.',
          ],
        },
      ],
    },
    {
      id: 'clean-submit',
      workElementNumber: 12,
      description: 'Clean debris from Console. Submit for build up visual',
      references: ['WI 5.7.2-01'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'document-discrepancies',
          text: 'All discrepancies/deviations documented with an MRCA#',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Notify Team Leader/Lead of any shortages, issues and the console is ready for visual inspection. Team Leader/Lead will assign.',
          ],
        },
      ],
    },
    {
      id: 'stamp-complete',
      workElementNumber: 13,
      description: 'Stamp as Complete',
      references: ['WI 5.7.2-01'],
      requiresAuditor: true,
      auditorReference: 'Auditor: The Visual is Completed. Tally Discrepancies below. Give this sheet to Team Leader',
      cycleTime: '0:05',
      hasTimeTracking: false,
      supportsMultiBadge: false,
      processSteps: [],
    },
  ],
  headerFields: CONSOLE_HEADER_FIELDS,
  references: ['WI 5.7.2-01', 'WI 5.7.2-05'],
  footerText: 'Caterpillar: Confidential Green',
  pageCount: 2,
  supportsTabletMode: true,
  computedFields: [
    { fieldId: 'pdNumber', sourcePath: 'project.pdNumber', allowOverride: true },
    { fieldId: 'projectName', sourcePath: 'project.name', allowOverride: true },
    { fieldId: 'unit', sourcePath: 'assignment.unit', allowOverride: true },
    { fieldId: 'bays', sourcePath: 'assignment.bays', allowOverride: true },
    { fieldId: 'revision', sourcePath: 'project.revision', allowOverride: true },
  ],
  overridePolicy: {
    overridableFields: ['pdNumber', 'projectName', 'unit', 'bays', 'date', 'revision'],
    requiresOverrideReason: false,
    logOverrides: true,
    warnAfterOverrideCount: 3,
  },
}

export const CONSOLE_CROSS_WIRE_TEMPLATE: SwsTemplateDefinition = {
  id: 'CONSOLE_CROSS_WIRE',
  swsIpvId: 'SWS-IPV_D380_ASSY_CON CROSS WIRE _B.1',
  name: 'Console Cross Wire',
  shortLabel: 'Console Cross Wire',
  description: 'Assembly for Console Cross Wire',
  category: 'CROSS_WIRE',
  stageScopes: ['CROSS_WIRING'],
  revisionLevel: 'B.1',
  revisionDate: '07/16/2024',
  processDescription: 'Assembly For Console Cross Wire',
  detectionPatterns: [
    {
      type: 'ENCLOSURE_TYPE',
      pattern: /CONSOLE|CON/i,
      confidence: 'MEDIUM',
      priority: 5,
    },
    {
      type: 'KEYWORD',
      pattern: /CONSOLE\s*CROSS|CON\s*CROSS|CROSS\s*WIRE.*CONSOLE/i,
      keywords: ['CONSOLE CROSS', 'CON CROSS'],
      confidence: 'HIGH',
      priority: 20,
    },
  ],
  sections: [
    {
      id: 'fill-paperwork',
      workElementNumber: 1,
      description: 'Fill out paperwork. Pre-Rout wire bundles between panels',
      symbol: 'WI',
      references: ['WI 5.3.0.5-02', 'QAS 503'],
      requiresAuditor: false,
      cycleTime: '',
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'fill-project-info',
          text: 'Fill in the Project information above on this form.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'verify-auditor-stamps',
          text: 'Ensure Auditor stamps are complete for Console Build Up prior to starting the wiring. Notify Team Leader if not completed.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'verify-revision',
          text: 'Verify the latest revision. Note cover sheet for any special requirements.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'stamp-working-copy',
          text: 'Stamp working copy of wire list and layout drawing. Highlight your badge number with the same color you will use on the wire list.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'verify-routing',
          text: 'For multi unit project, verify routing on the first unit. Notify Team Leader if incorrect.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'door-routing',
      workElementNumber: 2,
      description: 'Door Routing',
      references: ['QAS 503', 'QAS 505'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: true,
      notes: ['Ensure you follow the routing plan. Conduct a required pull test on each wire installed.'],
      processSteps: [
        {
          id: 'route-left-door',
          text: 'Route and terminate any wires that will remain on the door starting with the left door. If AC wires are present, maintain the AC/DC separation.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Route wires to harnessing point. There could be more than one harness for ease of routing or to maintain required separation.',
            'Measure and cut expando sleeving for harness (clamp to clamp, no grounds or cables in sleeving).',
            'Create harness from door to console. Check to make sure the harness does not interfere with the door closing or any components.',
            'Repeat for right door and any remaining doors that will require a harness.',
          ],
        },
      ],
    },
    {
      id: 'wiring-termination',
      workElementNumber: 3,
      description: 'Wiring Termination',
      references: ['QAS 503', 'QAS 505'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: true,
      notes: ['Ensure you follow the routing plan. Conduct a required pull test on each wire installed.', 'Start harness wiring from the doors in, left to right, top to bottom. Cut panduct fingers as needed for routing.'],
      processSteps: [
        {
          id: 'terminate-wires',
          text: 'Terminate wires using the wiring list used on the table for each panel. Any wire that will terminate with other wires of the same reference numbers that has already been visually checked, should be marked with blue tape.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'terminate-cables',
          text: 'Terminate all wire cables. Ensure labels are visible.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'spiral-wrap',
          text: 'Spiral wrap any wires that will cross any IS wire channel.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'grounds',
      workElementNumber: 4,
      description: 'Install, Route and Terminate Grounds',
      references: ['QAS 503', 'QAS 505', 'QAS 834', 'QAS 850'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'verify-grounds',
          text: 'Verify routing, gauge, and color of ground wires to be installed. Install and route ground wires.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Spiral wrap any wires that will cross any IS wire channel.',
            'Install ground wire labels. Follow shop floor label examples.',
          ],
        },
      ],
    },
    {
      id: 'keyboard-tray',
      workElementNumber: 5,
      description: 'Install Keyboard Tray If using the -30(x) Display or a 1 Bay Console',
      references: ['QAS 500', 'QAS 503', 'QAS 505'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'install-keyboard-tray',
          text: 'Install Keyboard tray.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Put keyboard inside tray and rout the USB cord to the HMI (no loops).',
            'Ensure inside tray slides back and forth with no binding and locks in the open position. Install foam padding.',
          ],
        },
      ],
    },
    {
      id: 'comm-cables',
      workElementNumber: 6,
      description: 'Communication Cables (Ethernet, Torque Meter, BN3500, etc.)',
      references: ['QAS 503', 'QAS 505', 'QAS 834'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'measure-cables',
          text: 'Measure cable lengths, they should be as close as possible to the correct length.',
          isKeyPoint: false,
          requiresCheckOff: true,
          subSteps: [
            'Route communication cables from door in and left to right. Use velcro to secure cables to the harness.',
            'Ensure communication cables are routed neatly on top of wires and cables. Maintain proper bend radius when connected.',
            'Install labels on the communication cables:',
          ],
          notes: [
            'Communication labels should be in a size 9 font.',
            'Labels should match the direction of the blue reference I.D.',
            'Place labels 1/4" from the connector.',
          ],
        },
      ],
    },
    {
      id: 'gather-materials',
      workElementNumber: 7,
      description: 'Gather all Materials',
      symbol: 'WI',
      references: ['WI 5.7.2-01'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'organize-folder',
          text: 'Ensure console folder is organized with all the wiring list/diagrams, layouts, and all SWS/IPV paperwork.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'consolidate-extra',
          text: 'Extra hardware/software is consolidated into a box and put in the proper location',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'keys-present',
          text: 'All keys are present with their respective component (TCP, PLC, and console door keys attached to the console)',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'clean-complete',
      workElementNumber: 8,
      description: 'Clean the debris and complete the panel',
      symbol: 'WI',
      references: ['WI 5.7.2-01'],
      requiresAuditor: false,
      hasTimeTracking: true,
      supportsMultiBadge: false,
      processSteps: [
        {
          id: 'remove-cable-ties',
          text: 'Remove excess cable ties from console/panduct. Only keep those that used to shape and route the harness and hold ground wires.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'remove-cover',
          text: 'Ensure any material used to cover the Power Supply has been removed prior to test.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'document-shortages',
          text: 'Ensure all shortages are documented. All discrepancies/deviations documented with an MRCA#',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'verify-wired',
          text: 'Look over Console and verify it is completely wired per wire list.',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
        {
          id: 'notify-lead',
          text: 'Notify Team Leader/Lead of any shortages, issues and the Console is ready for visual inspection. (Team Leader/Lead will assign)',
          isKeyPoint: false,
          requiresCheckOff: true,
        },
      ],
    },
    {
      id: 'stamp-complete',
      workElementNumber: 9,
      description: 'Stamp as Complete',
      symbol: 'WI',
      references: ['WI 5.7.2-01'],
      requiresAuditor: true,
      auditorReference: 'Auditor: The Visual is Completed Including a Wire Pull Test on all Crosswires.* Tally Discrepancies below. Give this sheet to Team Leader',
      cycleTime: '',
      hasTimeTracking: false,
      supportsMultiBadge: false,
      processSteps: [],
    },
  ],
  headerFields: CONSOLE_HEADER_FIELDS,
  references: ['WI 5.7.2-01', 'WI 5.7.2-05'],
  footerText: 'Caterpillar: Confidential Green',
  pageCount: 2,
  supportsTabletMode: true,
  computedFields: [
    { fieldId: 'pdNumber', sourcePath: 'project.pdNumber', allowOverride: true },
    { fieldId: 'projectName', sourcePath: 'project.name', allowOverride: true },
    { fieldId: 'unit', sourcePath: 'assignment.unit', allowOverride: true },
    { fieldId: 'bays', sourcePath: 'assignment.bays', allowOverride: true },
    { fieldId: 'revision', sourcePath: 'project.revision', allowOverride: true },
  ],
  overridePolicy: {
    overridableFields: ['pdNumber', 'projectName', 'unit', 'bays', 'date', 'revision'],
    requiresOverrideReason: false,
    logOverrides: true,
    warnAfterOverrideCount: 3,
  },
}

// ============================================================================
// TEMPLATE REGISTRY
// ============================================================================

export const SWS_TEMPLATE_REGISTRY: Record<SwsTemplateId, SwsTemplateDefinition> = {
  PANEL_BUILD_WIRE: PANEL_BUILD_WIRE_TEMPLATE,
  BASIC_BLANK_PANEL: BASIC_BLANK_PANEL_TEMPLATE,
  BOX_BUILD_UP: BOX_BUILD_UP_TEMPLATE,
  BOX_CROSS_WIRE: BOX_CROSS_WIRE_TEMPLATE,
  CONSOLE_BUILD_UP_PANEL_HANG: CONSOLE_BUILD_UP_PANEL_HANG_TEMPLATE,
  CONSOLE_CROSS_WIRE: CONSOLE_CROSS_WIRE_TEMPLATE,
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getSwsTemplate(swsType: SwsTemplateId): SwsTemplateDefinition {
  return SWS_TEMPLATE_REGISTRY[swsType]
}

export function getAllSwsTemplates(): SwsTemplateDefinition[] {
  return Object.values(SWS_TEMPLATE_REGISTRY)
}

export function getSwsTemplatesByCategory(category: SwsCategory): SwsTemplateDefinition[] {
  return Object.values(SWS_TEMPLATE_REGISTRY).filter(t => t.category === category)
}

export function getSwsTemplatesByStage(stageScope: SwsStageScope): SwsTemplateDefinition[] {
  return Object.values(SWS_TEMPLATE_REGISTRY).filter(t =>
    t.stageScopes.includes(stageScope)
  )
}

export function getCrossWireTemplates(): SwsTemplateDefinition[] {
  return [BOX_CROSS_WIRE_TEMPLATE, CONSOLE_CROSS_WIRE_TEMPLATE]
}

// Re-export types for convenience
export type { SwsCategory, SwsStageScope } from '@/types/d380-sws'
